export type IconOption = {
  value: string;
  label: string;
};

export const ICONS: IconOption[] = [
  { value: '', label: 'None' },
  { value: '💻', label: 'Laptop' },
  { value: '🖥️', label: 'Desktop' },
  { value: '⌨️', label: 'Keyboard' },
  { value: '🖱️', label: 'Mouse' },
  { value: '📱', label: 'Phone' },
  { value: '🔧', label: 'Wrench' },
  { value: '⚙️', label: 'Settings' },
  { value: '🔌', label: 'Plug' },
  { value: '💾', label: 'Save' },
  { value: '📡', label: 'Antenna' },
  { value: '🤖', label: 'Robot' },
  { value: '📚', label: 'Books' },
  { value: '📖', label: 'Open book' },
  { value: '🎓', label: 'Graduation' },
  { value: '🧠', label: 'Brain' },
  { value: '🔬', label: 'Microscope' },
  { value: '🧪', label: 'Test tube' },
  { value: '📐', label: 'Ruler' },
  { value: '✏️', label: 'Pencil' },
  { value: '📝', label: 'Notepad' },
  { value: '🏋️', label: 'Dumbbell' },
  { value: '🤸', label: 'Gymnastics' },
  { value: '🏃', label: 'Running' },
  { value: '💪', label: 'Muscle' },
  { value: '🧘', label: 'Yoga' },
  { value: '📊', label: 'Chart' },
  { value: '📈', label: 'Growth' },
  { value: '💼', label: 'Briefcase' },
  { value: '🤝', label: 'Handshake' },
  { value: '📋', label: 'Clipboard' },
  { value: '💡', label: 'Idea' },
  { value: '🎯', label: 'Target' },
  { value: '🚀', label: 'Rocket' },
  { value: '🎨', label: 'Palette' },
  { value: '🎵', label: 'Music' },
  { value: '🎬', label: 'Film' },
  { value: '📷', label: 'Camera' },
  { value: '🌿', label: 'Plant' },
  { value: '🌱', label: 'Sprout' },
  { value: '⚡', label: 'Lightning' },
  { value: '🔥', label: 'Fire' },
  { value: '💧', label: 'Water' },
  { value: '🌙', label: 'Moon' },
  { value: '⭐', label: 'Star' },
  { value: '🏠', label: 'Home' },
  { value: '🔑', label: 'Key' },
  { value: '📌', label: 'Pin' },
  { value: '🎁', label: 'Gift' },
  { value: '🏆', label: 'Trophy' },
  { value: '💬', label: 'Chat' },
  { value: '🗓️', label: 'Calendar' },
  { value: '🔗', label: 'Link' },
];
