name: Website Deploy

on:
  push:
    branches:
    - dev
    - main
    - feature/workflows
    - feature/docker

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Backend .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > backend/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> backend/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env
          echo "DB_SSL_MODE=${{ secrets.DB_SSL_MODE }}" >> backend/.env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> backend/.env
          echo "PORT=${{ secrets.PORT }}" >> backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> backend/.env
          echo "STORAGE_TYPE=${{ secrets.STORAGE_TYPE }}" >> backend/.env
          echo "LOCAL_PATH=${{ secrets.LOCAL_PATH }}" >> backend/.env
          echo "LOCAL_URL=${{ secrets.LOCAL_URL }}" >> backend/.env
          echo "TOKEN_TELEGRAM_NOTIFICATIONS=${{ secrets.TOKEN_TELEGRAM_NOTIFICATIONS }}" >> backend/.env
          echo "CHAT_ID_TELEGRAM_BOT_NOTIFICATIONS=${{ secrets.CHAT_ID_TELEGRAM_BOT_NOTIFICATIONS }}" >> backend/.env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> backend/.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> backend/.env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> backend/.env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> backend/.env
          echo "SMTP_FROM_EMAIL=${{ secrets.SMTP_FROM_EMAIL }}" >> backend/.env
          echo "SMTP_FROM_NAME=${{ secrets.SMTP_FROM_NAME }}" >> backend/.env
          echo "FRONTEND_BASE_URL=${{ secrets.FRONTEND_BASE_URL }}" >> backend/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> backend/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> backend/.env
          echo "CLIENT_ID_GITHUB=${{ secrets.CLIENT_ID_GITHUB }}" >> backend/.env
          echo "CLIENT_SECRET_GITHUB=${{ secrets.CLIENT_SECRET_GITHUB }}" >> backend/.env
          echo "GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}" >> backend/.env
          echo "CALLBACK_URL_GITHUB=${{ secrets.CALLBACK_URL_GITHUB }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env
          
      - name: Create .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build and Deploy
        run: |
          docker compose down
          docker compose up -d --build
