name: Website Deploy

on:
  push:
    branches:
    - dev
    - main
    - feature/workflows
    - feature/docker

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Backend .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > backend/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> backend/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env
          echo "DB_SSL_MODE=${{ secrets.DB_SSL_MODE }}" >> backend/.env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> backend/.env
          echo "PORT=${{ secrets.PORT }}" >> backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> backend/.env
          echo "STORAGE_TYPE=${{ secrets.STORAGE_TYPE }}" >> backend/.env
          echo "LOCAL_PATH=${{ secrets.LOCAL_PATH }}" >> backend/.env
          echo "LOCAL_URL=${{ secrets.LOCAL_URL }}" >> backend/.env
          echo "TOKEN_TELEGRAM_NOTIFICATIONS=${{ secrets.TOKEN_TELEGRAM_NOTIFICATIONS }}" >> backend/.env
          echo "CHAT_ID_TELEGRAM_BOT_NOTIFICATIONS=${{ secrets.CHAT_ID_TELEGRAM_BOT_NOTIFICATIONS }}" >> backend/.env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> backend/.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> backend/.env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> backend/.env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> backend/.env
          echo "SMTP_FROM_EMAIL=${{ secrets.SMTP_FROM_EMAIL }}" >> backend/.env
          echo "SMTP_FROM_NAME=${{ secrets.SMTP_FROM_NAME }}" >> backend/.env

      - name: Create .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env

      - name: Build and Deploy
        run: |
          docker compose down
          docker compose up -d --build
          
          sleep 20
        
          echo "=== Status ==="
          docker compose ps
          
          if ! docker compose ps --filter "name=team-track-site-backend" --format "table {{.Name}}\t{{.State}}" | grep -q "team-track-site-backend.*Up"; then
            echo "Crash. Logs..."
            echo "=== logs team-track-site-backend ==="
            docker-compose logs team-track-site-backend
            exit 1
          fi
          
          echo "Successfully started containers"
          echo "===  ==="
          docker compose logs --tail=20 team-track-site-backend

